### PR TITLE
Added setSocketBufferSize(sbs) to the Camera class.

### PR DESCRIPTION
**Pull request by aparenti**

### CODE REVIEW

**Comment by esrf-bliss** [comment]
Thanks for your work,

SEB

**Comment by esrf-bliss** [comment]
Hi Andrea,
thanks for the commit. Could you tell us what's the need of changing the buffer size? Did you get
some performance issues?
Cheers
Laurent

**Comment by aparenti** [comment]
Hi Laurent,

recently I compiled LImA on a CentOS 7.1 PC, what I observed when 
preparing the acquisition was the error "SocketBufferSize not valid!". I 
found its description in 
http://www.baslerweb.com/en/support/knowledge-base/frequently-asked-questions?faq-id=91342

When I checked the buffer size with PylonViewer I saw it was set to the 
default value (2048), which is too large. This is the reason why I needed 
a way to set the buffer size manually.

Cheers,
 	Andrea

**Comment by esrf-bliss** [comment]
ok, I see, they say (basler knowlege-base) that pb result of a reading failure of the maximum buffer size
supported by the system.  
So it could be nice to have this pylon property better managed, or if you are using the python tango server to create a property for setting a buffer size which will overwrite the wrong value.
Did you change the Tango camera plugin as well ?

Cheers.
Laurent

**Comment by aparenti** [comment]
I did not change the Tango camera plugin, since I use LImA in a different control system. I should be able do it, but I am not the best one since I could not test it.

Cheers,
Andrea

**Comment by esrf-bliss** [comment]
No problem Andrea, we will do it later if we need it.

SEB

**Pull request merged**
